[telegram]
token = "8557457495:AAFkMEiDwWwfYm9N2Zm3A1QKpY_eQVqWc5Y"
workers = 1
admins = [8294554523]
admins_only = false
maintenance_mode = false
persistent_temp_data = true

[pyrogram]
enabled = false
api_id = 0
api_hash = ""

[sqlite]
filename = "stickersbot.sqlite"

[bot]
sourcecode = ""
issues = ""
channel = "lifeCitychannel"
